on: [push, pull_request]
name: Test
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Setup modules
        run: |
          go mod tidy
      - name: Run Test
        run: |
          go test -race